name: portfolio
static_sites:
  - name: portfolio
    git:
      repo_clone_url: https://github.com/Goldxberg/portfolio.git
      branch: main
    source_dir: /
    build_command: npm run build
    output_dir: dist
    index_document: index.html
